rule turla_outlook_pdf {   
       meta:   
           author      = "ESET Research"   
           date        = "22-08-2018"   
           description = "Detect PDF documents generated by Turla Outlook malware"   
           reference   = "https://www.welivesecurity.com/wp-content/uploads/2018/08/Eset-Turla-Outlook-Backdoor.pdf"   
           source = "https://github.com/eset/malware-ioc/"   
           contact = "github@eset.com"   
           license = "BSD 2-Clause"     
       strings:   
           $s1 = "Adobe PDF Library 9.0" ascii wide nocase   
           $s2 = "Acrobat PDFMaker 9.0"  ascii wide nocase   
           $s3 = {FF D8 FF E0 00 10 4A 46 49 46}   
           $s4 = {00 3F 00 FD FC A2 8A 28 03 FF D9}   
           $s5 = "W5M0MpCehiHzreSzNTczkc9d" ascii wide nocase   
           $s6 = "PDF-1.4" ascii wide nocase   
       condition:   
           5 of them   
   }